# Data Preprocessing

## Importing the libraries

In [ ]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

## Importing the dataset

In [ ]:
df = pd.read_csv('dataset.csv')

In [ ]:
X = df.iloc[:, 1:-1].values
y = df.iloc[:, -1].values

In [ ]:
print(X)

[['verb' 7 4 ... 0 0 2]
 ['noun' 2 1 ... 0 580 11]
 ['adjective' 4 2 ... 0 0 11]
 ...
 ['noun' 6 4 ... 0 0 4]
 ['number' 9 0 ... 0 0 1]
 ['noun' 6 2 ... 0 0 3]]


In [ ]:
print(y)

['b2' 'a2' 'a2' ... 'b1' 'a2' 'b2']


## Encoding


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(X)

[[0.0 0.0 0.0 ... 0 0 2]
 [0.0 0.0 0.0 ... 0 580 11]
 [1.0 0.0 0.0 ... 0 0 11]
 ...
 [0.0 0.0 0.0 ... 0 0 4]
 [0.0 0.0 0.0 ... 0 0 1]
 [0.0 0.0 0.0 ... 0 0 3]]


In [ ]:
print(y)

[3 1 1 ... 2 1 3]


## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [ ]:
print(X_train)

[[0.0 0.0 0.0 ... 0 464 4]
 [0.0 0.0 0.0 ... 0 0 3]
 [0.0 0.0 0.0 ... 0 0 4]
 ...
 [0.0 0.0 0.0 ... 0 323 4]
 [1.0 0.0 0.0 ... 0 0 20]
 [0.0 0.0 0.0 ... 0 0 2]]


In [ ]:
print(X_test)

[[0.0 0.0 0.0 ... 0 464 71]
 [0.0 0.0 0.0 ... 0 356 4]
 [0.0 0.0 0.0 ... 0 0 5]
 ...
 [0.0 0.0 0.0 ... 0 0 4]
 [0.0 0.0 0.0 ... 0 0 3]
 [0.0 0.0 0.0 ... 0 0 5]]


In [ ]:
print(y_train)

[3 2 2 ... 1 0 0]


In [ ]:
print(y_test)

[3 4 2 1 4 4 3 1 4 0 4 4 2 3 4 4 3 4 2 0 4 0 1 3 0 3 1 4 1 0 2 3 3 0 4 4 4
 1 3 4 0 3 0 1 0 3 1 4 3 3 1 1 0 3 3 4 3 0 2 4 0 3 1 4 2 4 0 3 1 1 3 4 2 0
 3 2 4 3 4 4 0 2 3 4 2 4 3 1 1 0 2 3 3 4 4 0 0 0 0 4 4 4 4 3 0 0 4 1 1 0 4
 3 0 4 0 3 2 1 1 0 4 4 1 1 2 4 0 4 3 2 2 3 4 1 3 2 0 2 4 1 4 4 3 3 3 1 0 3
 4 0 0 1 3 1 4 4 1 2 1 4 4 0 0 3 3 3 0 4 4 1 3 0 3 1 3 4 2 1 3 1 3 3 3 3 3
 2 3 1 2 0 3 1 3 0 2 3 4 0 3 2 2 1 3 4 3 0 0 4 3 2 0 0 3 2 4 1 0 4 0 4 4 4
 3 3 3 3 4 1 1 3 2 3 2 0 3 0 3 0 1 4 3 1 0 0 3 3 4 1 0 4 3 1 4 3 2 1 0 4 1
 0 1 0 2 0 3 3 0 2 3 1 0 3 0 0 3 0 3 3 0 4 1 3 3 0 3 3 1 3 4 4 0 4 3 2 4 4
 4 3 3 2 3 0 2 4 2 3 3 0 3 1 4 4 2 3 4 4 1 3 0 4 4 2 2 4 1 3 1 1 0 4 3 1 3
 0 2 3 3 3 2 1 4 2 2 0 4 0 1 2 1 4 2 2 1 4 3 4 0 4 3 0 3 3 4 3 4 4 4 3 1 1
 4 2 3 1 3 1 3 3 2 4 3 4 0 4 2 4 2 2 0 1 1 4 4 0 4 4 1 3 2 4 0 0 3 3 3 2 0
 1 4 1 0 1 3 3 3 0 3 1 3 4 4 3 4 1 3 2 3 0 1 4 3 3 4 2 3 2 2 0 0 4 4 3 4 1
 4 1 4 4 2 3 2 1 0 1 0 3 4 1 0 1 0 4 4 4 2 4 4 2 4 4 3 4 1 2 1 4 0 1 0 4 1
 4 4 3 2 4 4 2 0 3 0 0 3 

## Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:, 9:] = sc.fit_transform(X_train[:, 9:])
X_test[:, 9:] = sc.transform(X_test[:, 9:])

In [ ]:
print(X_train)

[[0.0 0.0 0.0 ... -0.25824238955886414 0.15301457120237313
  -0.4315313831333375]
 [0.0 0.0 0.0 ... -0.25824238955886414 -0.45481347147853396
  -0.47932395691964746]
 [0.0 0.0 0.0 ... -0.25824238955886414 -0.45481347147853396
  -0.4315313831333375]
 ...
 [0.0 0.0 0.0 ... -0.25824238955886414 -0.03169179521574734
  -0.4315313831333375]
 [1.0 0.0 0.0 ... -0.25824238955886414 -0.45481347147853396
  0.333149797447622]
 [0.0 0.0 0.0 ... -0.25824238955886414 -0.45481347147853396
  -0.5271165307059574]]


In [ ]:
print(X_test)

[[0.0 0.0 0.0 ... -0.25824238955886414 0.15301457120237313
  2.7705710605494307]
 [0.0 0.0 0.0 ... -0.25824238955886414 0.011537354371472344
  -0.4315313831333375]
 [0.0 0.0 0.0 ... -0.25824238955886414 -0.45481347147853396
  -0.3837388093470275]
 ...
 [0.0 0.0 0.0 ... -0.25824238955886414 -0.45481347147853396
  -0.4315313831333375]
 [0.0 0.0 0.0 ... -0.25824238955886414 -0.45481347147853396
  -0.47932395691964746]
 [0.0 0.0 0.0 ... -0.25824238955886414 -0.45481347147853396
  -0.3837388093470275]]


# Random Forest Classification

## Training the Random Forest Classification model on the Training set

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(criterion='entropy', max_depth=8, max_features='auto', n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_forest.py:424: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(


RandomForestClassifier(criterion='entropy', max_depth=8, max_features='auto',
                       random_state=42)

## Applying Grid Search and k-Fold Cross Validation

Note: The code below may take a couple of minutes to run

In [ ]:
from sklearn.model_selection import GridSearchCV
parameters = { 
    'n_estimators': [5, 10 ,25, 50, 75, 100],
    'max_features': ['auto', 'sqrt', 'log2'],
    'max_depth' : [4,5,6,7,8],
    'criterion' :['gini', 'entropy']
}

grid_search = GridSearchCV(estimator = rf,
                           param_grid = parameters,
                           scoring = 'accuracy',
                           cv = 5)
grid_search.fit(X_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("Best Accuracy: {:.2f} %".format(best_accuracy*100))
print("Best Parameters:", best_parameters)

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_forest.py:424: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_forest.py:424: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(
/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_forest.py:424: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomFor

Best Accuracy: 52.08 %
Best Parameters: {'criterion': 'gini', 'max_depth': 8, 'max_features': 'auto', 'n_estimators': 75}


In [ ]:
classifier = RandomForestClassifier(criterion =best_parameters['criterion'], max_depth =best_parameters['max_depth'], max_features =best_parameters['max_features'], n_estimators =best_parameters['n_estimators'])
classifier.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/ensemble/_forest.py:424: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'` or remove this parameter as it is also the default value for RandomForestClassifiers and ExtraTreesClassifiers.
  warn(


RandomForestClassifier(max_depth=8, max_features='auto', n_estimators=75)

## Predicting the Test set results

In [ ]:
y_pred = rf.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[3 3]
 [3 4]
 [3 2]
 ...
 [3 2]
 [4 4]
 [0 0]]


## Making the Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[118  31   3  10   4]
 [ 45  62  13  34   6]
 [ 13  32  31  59  10]
 [  6  18  29 159  55]
 [  0   3   2  74 175]]
              precision    recall  f1-score   support

           0       0.65      0.71      0.68       166
           1       0.42      0.39      0.41       160
           2       0.40      0.21      0.28       145
           3       0.47      0.60      0.53       267
           4       0.70      0.69      0.69       254

    accuracy                           0.55       992
   macro avg       0.53      0.52      0.52       992
weighted avg       0.54      0.55      0.54       992



In [ ]:
accuracy_score(y_test, y_pred)

0.5493951612903226

In [ ]:
pd.crosstab(y_test, y_pred)

col_0    0   1   2    3    4
row_0                       
0      118  31   3   10    4
1       45  62  13   34    6
2       13  32  31   59   10
3        6  18  29  159   55
4        0   3   2   74  175